### PR TITLE
Add documentation for aliasDangerous

### LINKED ISSUE #3: Rewire alias from outside of root folder?
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@libcommon/*": ["../../shared/common/*"]
    }
  }
}
```
Is there a way of making it work for imports outside of the current folder? It works on the node side with `ts-node`but in `cra` not yet..

### PR DESCRIPTION
**Pull request by JollyGoodHolly**
Fixes #3

### CODE REVIEW

**Comment by oklas** [comment]
actually this fixes #6

**Comment by oklas** [comment]
please reopen #4

**Comment by JollyGoodHolly** [comment]
@oklas #4 cannot be reopened because I deleted the fork (due to corporate restrictions I cannot use Git, so I edit files on the web UI, which does not allow pulling or rebasing). If you need specific edits, you can copy them from the commits. I don't need attribution.

**Comment by oklas** [comment]
Git allows to specify attributes it is not only question. I dont see a way to access commits or take patch from web ui here. I just to take edits you have made because I see you have better feel of english.

**Comment by JollyGoodHolly** [comment]
@oklas I re-created it [here](https://pastebin.com/1nbi2PGN). You can commit without merge and then close the PR and issue.

**Comment by oklas** [comment]
@JollyGoodHolly, thanks, merged

**Comment by shadow-identity** [comment]
Hey @oklas,
I think something went wrong because there is still no mentioning of aliasDangerous in the current master head.

**Pull request closed without merging**
